#theme: jekyll-theme-slate
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
title: Mehery
description: MeherY Release Notes
logo: "https://cdn.jsdelivr.net/gh/mehery-soccom/mehery-content@main/static/app/logo/bg-x-logo.png"
aux_links:
  "Create Account":
    - "//app.mehery.com"
